[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

# SPA redirect rule - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
